/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal.shape.calculator;

import java.text.DecimalFormat;
import javax.swing.ImageIcon;

/**
 *
 * @author rexiepimentelMBP
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    ShapesCalculatorUI shapesCalculatorUI = new ShapesCalculatorUI();
    ShapesFormula shapesFormula = new ShapesFormula();
    DecimalFormat df = new DecimalFormat("#.00");
    
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelApplicationLogo = new javax.swing.JPanel();
        panelShapeSelection = new javax.swing.JTabbedPane();
        scrollPanel2dShapes = new javax.swing.JScrollPane();
        panel2dShapes = new javax.swing.JPanel();
        btnCircle = new javax.swing.JButton();
        btnEllipse = new javax.swing.JButton();
        btnSquare = new javax.swing.JButton();
        btnRectangle = new javax.swing.JButton();
        btnTriangle = new javax.swing.JButton();
        btnPentagon = new javax.swing.JButton();
        btnHexagon = new javax.swing.JButton();
        btnOctagon = new javax.swing.JButton();
        btnNonagon = new javax.swing.JButton();
        btnDecagon = new javax.swing.JButton();
        btnParallelogram = new javax.swing.JButton();
        btnTrapezoid = new javax.swing.JButton();
        btnRhombus = new javax.swing.JButton();
        scrollPanel3dShapes = new javax.swing.JScrollPane();
        panel3dShapes = new javax.swing.JPanel();
        btnCube = new javax.swing.JButton();
        btnCuboid = new javax.swing.JButton();
        btnTriangularPrism = new javax.swing.JButton();
        btnSquareBasedPyramid = new javax.swing.JButton();
        btnCylinder = new javax.swing.JButton();
        btnCone = new javax.swing.JButton();
        btnSphere = new javax.swing.JButton();
        btnHemisphere = new javax.swing.JButton();
        panelShapeFormula = new javax.swing.JPanel();
        lblShapeFormula = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblSelectedShapeDiagram = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblGiven = new javax.swing.JLabel();
        ftfGiven = new javax.swing.JFormattedTextField();
        btnCalculate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        lblAnswer = new javax.swing.JLabel();
        panelShapeName = new javax.swing.JPanel();
        lblShapeName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        panelApplicationLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelApplicationLogoLayout = new javax.swing.GroupLayout(panelApplicationLogo);
        panelApplicationLogo.setLayout(panelApplicationLogoLayout);
        panelApplicationLogoLayout.setHorizontalGroup(
            panelApplicationLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        panelApplicationLogoLayout.setVerticalGroup(
            panelApplicationLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        getContentPane().add(panelApplicationLogo);
        panelApplicationLogo.setBounds(0, 0, 200, 120);

        panelShapeSelection.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        scrollPanel2dShapes.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        btnCircle.setText("Circle");
        btnCircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCircleActionPerformed(evt);
            }
        });

        btnEllipse.setText("Ellipse");
        btnEllipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEllipseActionPerformed(evt);
            }
        });

        btnSquare.setText("Square");
        btnSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareActionPerformed(evt);
            }
        });

        btnRectangle.setText("Rectangle");
        btnRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectangleActionPerformed(evt);
            }
        });

        btnTriangle.setText("Triangle");
        btnTriangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriangleActionPerformed(evt);
            }
        });

        btnPentagon.setText("Pentagon");
        btnPentagon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPentagonActionPerformed(evt);
            }
        });

        btnHexagon.setText("Hexagon");
        btnHexagon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHexagonActionPerformed(evt);
            }
        });

        btnOctagon.setText("Octagon");
        btnOctagon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOctagonActionPerformed(evt);
            }
        });

        btnNonagon.setText("Nonagon");
        btnNonagon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNonagonActionPerformed(evt);
            }
        });

        btnDecagon.setText("Decagon");
        btnDecagon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecagonActionPerformed(evt);
            }
        });

        btnParallelogram.setText("Parallelogram");
        btnParallelogram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParallelogramActionPerformed(evt);
            }
        });

        btnTrapezoid.setText("Trapezoid");
        btnTrapezoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrapezoidActionPerformed(evt);
            }
        });

        btnRhombus.setText("Rhombus");
        btnRhombus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRhombusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2dShapesLayout = new javax.swing.GroupLayout(panel2dShapes);
        panel2dShapes.setLayout(panel2dShapesLayout);
        panel2dShapesLayout.setHorizontalGroup(
            panel2dShapesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2dShapesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2dShapesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEllipse, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRectangle, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTriangle, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPentagon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHexagon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOctagon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNonagon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDecagon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnParallelogram, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrapezoid, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRhombus, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panel2dShapesLayout.setVerticalGroup(
            panel2dShapesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2dShapesLayout.createSequentialGroup()
                .addComponent(btnCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEllipse, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRectangle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTriangle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPentagon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHexagon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOctagon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNonagon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDecagon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnParallelogram, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrapezoid, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRhombus, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        scrollPanel2dShapes.setViewportView(panel2dShapes);

        panelShapeSelection.addTab("2D Shapes", scrollPanel2dShapes);

        scrollPanel3dShapes.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPanel3dShapes.setHorizontalScrollBar(null);

        btnCube.setText("Cube");
        btnCube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCubeActionPerformed(evt);
            }
        });

        btnCuboid.setText("Cuboid");
        btnCuboid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuboidActionPerformed(evt);
            }
        });

        btnTriangularPrism.setText("Triangular Prism");
        btnTriangularPrism.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriangularPrismActionPerformed(evt);
            }
        });

        btnSquareBasedPyramid.setText("Squared-Based Pyramid");
        btnSquareBasedPyramid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareBasedPyramidActionPerformed(evt);
            }
        });

        btnCylinder.setText("Cylinder");
        btnCylinder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCylinderActionPerformed(evt);
            }
        });

        btnCone.setText("Cone");
        btnCone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConeActionPerformed(evt);
            }
        });

        btnSphere.setText("Sphere");
        btnSphere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSphereActionPerformed(evt);
            }
        });

        btnHemisphere.setText("Hemisphere");
        btnHemisphere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHemisphereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3dShapesLayout = new javax.swing.GroupLayout(panel3dShapes);
        panel3dShapes.setLayout(panel3dShapesLayout);
        panel3dShapesLayout.setHorizontalGroup(
            panel3dShapesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3dShapesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3dShapesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCube, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCuboid, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTriangularPrism, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSquareBasedPyramid, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCylinder, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCone, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSphere, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHemisphere, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panel3dShapesLayout.setVerticalGroup(
            panel3dShapesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3dShapesLayout.createSequentialGroup()
                .addComponent(btnCube, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCuboid, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTriangularPrism, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSquareBasedPyramid, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCylinder, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCone, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSphere, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHemisphere, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        scrollPanel3dShapes.setViewportView(panel3dShapes);

        panelShapeSelection.addTab("3D Shapes", scrollPanel3dShapes);

        getContentPane().add(panelShapeSelection);
        panelShapeSelection.setBounds(0, 120, 200, 550);

        panelShapeFormula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblShapeFormula.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblShapeFormula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShapeFormula.setText("Selected Shape Formula");

        javax.swing.GroupLayout panelShapeFormulaLayout = new javax.swing.GroupLayout(panelShapeFormula);
        panelShapeFormula.setLayout(panelShapeFormulaLayout);
        panelShapeFormulaLayout.setHorizontalGroup(
            panelShapeFormulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShapeFormulaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblShapeFormula, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelShapeFormulaLayout.setVerticalGroup(
            panelShapeFormulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShapeFormulaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblShapeFormula)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(panelShapeFormula);
        panelShapeFormula.setBounds(200, 530, 950, 140);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        lblSelectedShapeDiagram.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectedShapeDiagram.setText("Selected Shape Diagram");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(lblSelectedShapeDiagram, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblSelectedShapeDiagram, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("Choose a Calculation");

        lblGiven.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblGiven.setText("given =");
        lblGiven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ftfGiven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ftfGiven.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        ftfGiven.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Find Area", "Find Perimeter" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblGiven, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfGiven))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGiven, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfGiven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate)
                    .addComponent(btnClear))
                .addGap(39, 39, 39))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblAnswer.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblAnswer.setForeground(new java.awt.Color(0, 0, 0));
        lblAnswer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnswer.setText("Answer");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(200, 60, 950, 470);

        lblShapeName.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblShapeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShapeName.setText("Selected Shape NAme");

        javax.swing.GroupLayout panelShapeNameLayout = new javax.swing.GroupLayout(panelShapeName);
        panelShapeName.setLayout(panelShapeNameLayout);
        panelShapeNameLayout.setHorizontalGroup(
            panelShapeNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShapeNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblShapeName, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelShapeNameLayout.setVerticalGroup(
            panelShapeNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShapeNameLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblShapeName)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(panelShapeName);
        panelShapeName.setBounds(200, 0, 950, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCircleActionPerformed
        // TODO add your handling code here:
        lblShapeFormula.setText(shapesFormula.circle());
        lblShapeName.setText("Circle");
        lblSelectedShapeDiagram.setIcon(new ImageIcon(getClass().getResource("/Images/CircleDiag.png")));
        lblGiven.setText("radius r=");
        
    }//GEN-LAST:event_btnCircleActionPerformed

    private void btnEllipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEllipseActionPerformed
        // TODO add your handling code here:
        lblShapeFormula.setText(shapesFormula.ellipse());
        
        
    }//GEN-LAST:event_btnEllipseActionPerformed

    private void btnSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSquareActionPerformed

    private void btnRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectangleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRectangleActionPerformed

    private void btnTriangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriangleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTriangleActionPerformed

    private void btnPentagonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPentagonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPentagonActionPerformed

    private void btnHexagonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHexagonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHexagonActionPerformed

    private void btnOctagonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOctagonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOctagonActionPerformed

    private void btnNonagonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNonagonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNonagonActionPerformed

    private void btnDecagonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecagonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDecagonActionPerformed

    private void btnParallelogramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParallelogramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnParallelogramActionPerformed

    private void btnTrapezoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrapezoidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrapezoidActionPerformed

    private void btnRhombusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRhombusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRhombusActionPerformed

    private void btnCubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCubeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCubeActionPerformed

    private void btnCuboidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuboidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCuboidActionPerformed

    private void btnTriangularPrismActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriangularPrismActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTriangularPrismActionPerformed

    private void btnSquareBasedPyramidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareBasedPyramidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSquareBasedPyramidActionPerformed

    private void btnCylinderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCylinderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCylinderActionPerformed

    private void btnConeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConeActionPerformed

    private void btnSphereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSphereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSphereActionPerformed

    private void btnHemisphereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHemisphereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHemisphereActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        try {
            //For Rounding: https://stackoverflow.com/questions/2808535/round-a-double-to-2-decimal-places
            //For Double Handler: https://stackoverflow.com/questions/49466030/how-to-convert-double-values-to-string-in-a-text-field
            double radius = Double.parseDouble(ftfGiven.getText());
            double diameter = radius * 2;
            double circumference = 2 * Math.PI * radius;
            double area = Math.PI * radius * radius;

            lblAnswer.setText("<html>Diameter = " + df.format(diameter) +
                "<br>Circumference = " + df.format(circumference) +
                "<br>Area = " + df.format(area) + "</html>");
        } catch (NumberFormatException ex) {
            lblAnswer.setText("Invalid radius. Please enter a number.");
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        ftfGiven.setText("");
        lblAnswer.setText("Answer");
    }//GEN-LAST:event_btnClearActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnCircle;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCone;
    private javax.swing.JButton btnCube;
    private javax.swing.JButton btnCuboid;
    private javax.swing.JButton btnCylinder;
    private javax.swing.JButton btnDecagon;
    private javax.swing.JButton btnEllipse;
    private javax.swing.JButton btnHemisphere;
    private javax.swing.JButton btnHexagon;
    private javax.swing.JButton btnNonagon;
    private javax.swing.JButton btnOctagon;
    private javax.swing.JButton btnParallelogram;
    private javax.swing.JButton btnPentagon;
    private javax.swing.JButton btnRectangle;
    private javax.swing.JButton btnRhombus;
    private javax.swing.JButton btnSphere;
    private javax.swing.JButton btnSquare;
    private javax.swing.JButton btnSquareBasedPyramid;
    private javax.swing.JButton btnTrapezoid;
    private javax.swing.JButton btnTriangle;
    private javax.swing.JButton btnTriangularPrism;
    private javax.swing.JFormattedTextField ftfGiven;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblAnswer;
    private javax.swing.JLabel lblGiven;
    private javax.swing.JLabel lblSelectedShapeDiagram;
    private javax.swing.JLabel lblShapeFormula;
    private javax.swing.JLabel lblShapeName;
    private javax.swing.JPanel panel2dShapes;
    private javax.swing.JPanel panel3dShapes;
    private javax.swing.JPanel panelApplicationLogo;
    private javax.swing.JPanel panelShapeFormula;
    private javax.swing.JPanel panelShapeName;
    private javax.swing.JTabbedPane panelShapeSelection;
    private javax.swing.JScrollPane scrollPanel2dShapes;
    private javax.swing.JScrollPane scrollPanel3dShapes;
    // End of variables declaration//GEN-END:variables
}
